version: '3.8'

name: arsha

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    networks:
      arsha:
        aliases:
          - api.service.arsha
    links:
      - redis
      # - redis-test
    depends_on:
      - redis
      # - redis-test
    ports:
      - '3000:3000'
  redis:
    image: 'redis:latest'
    # ports:
    #   - '6379:6379'
    networks:
      arsha:
        aliases:
          - redis.service.arsha
    volumes:
      - redis-data:/data
#  redis-test:
#    image: 'redis:latest'
#    ports:
#      - '6380:6379'
#    networks:
#      arsha:
#        aliases:
#          - redis-test.service.arsha

networks:
    arsha:
      driver: bridge

volumes:
    redis-data: