name: arsha

services:
  redis:
    image: redis:8-alpine
    ports:
    - '6379:6379'
    networks:
      arsha:
        aliases:
        - redis.service.arsha
        - redis
    volumes:
    - redis-data:/data

networks:
    arsha:

volumes:
    redis-data:
