name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy-image:
    runs-on: arsha
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/guy0090/bdo-api:latest
            ghcr.io/guy0090/bdo-api:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title=api.arsha.io
            org.opencontainers.image.description=Black Desert Online market API
            org.opencontainers.image.url=https://github.com/guy0090/api.arsha.io
